<!-- Generated by pkgdown: do not edit by hand -->
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>Retrospective stock assessment for FLSAM — retro • FLSAM</title>


<!-- jquery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<!-- Bootstrap -->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script>

<!-- Font Awesome icons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/all.min.css" integrity="sha256-nAmazAk6vS34Xqo0BSrTb+abbtFlgsFK7NKSi6o7Y78=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/v4-shims.min.css" integrity="sha256-6qHlizsOWFskGlwVOKuns+D1nB6ssZrHQrNj1wGplHc=" crossorigin="anonymous" />

<!-- clipboard.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script>

<!-- headroom.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/headroom.min.js" integrity="sha256-DJFC1kqIhelURkuza0AvYal5RxMtpzLjFhsnVIeuk+U=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script>

<!-- pkgdown -->
<link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script>




<meta property="og:title" content="Retrospective stock assessment for FLSAM — retro" />
<meta property="og:description" content="Performs a retrospective stock assessment for the desired years using
the FLSAM stock assessment method" />
<meta name="twitter:card" content="summary" />




<!-- mathjax -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script>

<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->



  </head>

  <body>
    <div class="container template-reference-topic">
      <header>
      <div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">FLSAM</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">2.1.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="http://github.com/flr/FLSAM">
    <span class="fa fa-github fa-lg"></span>
     
    Source
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li>
  <a href="../articles/index.html">Articles</a>
</li>
<li>
  <a href="../news/index.html">News</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="http://flr-project.org/">FLR</a>
</li>
      </ul>
      
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

      

      </header>

<div class="row">
  <div class="col-md-9 contents">
    <div class="page-header">
    <h1>Retrospective stock assessment for FLSAM</h1>
    
    <div class="hidden name"><code>retro.rd</code></div>
    </div>

    <div class="ref-description">
    <p>Performs a retrospective stock assessment for the desired years using
the FLSAM stock assessment method</p>
    </div>

    <pre class="usage"><span class='fu'><a href='retro.rd.html'>retro</a></span>(<span class='no'>stock</span>, <span class='no'>indices</span>, <span class='no'>control</span>, <span class='no'>retro</span>, <span class='no'>year.range</span>)</pre>

    <h2 class="hasAnchor" id="arguments"><a class="anchor" href="#arguments"></a>Arguments</h2>
    <table class="ref-arguments">
    <colgroup><col class="name" /><col class="desc" /></colgroup>
    <tr>
      <th>stock</th>
      <td><p>An <code><a href='FLSAM.html'>FLSAM</a></code> object</p></td>
    </tr>
    <tr>
      <th>indices</th>
      <td><p>An  <code>FLIndices</code> object</p></td>
    </tr>
    <tr>
      <th>control</th>
      <td><p>An <code><a href='FLSAM.control.html'>FLSAM.control</a></code> object</p></td>
    </tr>
    <tr>
      <th>retro</th>
      <td><p>An integer that specifies the number of retrospective years.
                Default value = 0. Only used if year.range is not specified.</p></td>
    </tr>
    <tr>
      <th>year.range</th>
      <td><p>Numeric vector of years to perform the assessment</p></td>
    </tr>
    </table>

    <h2 class="hasAnchor" id="details"><a class="anchor" href="#details"></a>Details</h2>

    <p>The argument 'year.range' is a numeric vector of years for which the assessment is to be performed.
If this is not specified the integer "retro" used (default value = 0). If retro = 0
the assessment is run for final year only. If retro = 1, the assessment is run for the
penultimate and final year and so on.</p>
    <h2 class="hasAnchor" id="value"><a class="anchor" href="#value"></a>Value</h2>

    <p>Returns an FLSAMs object. Individual assessments that failed to converge are not included in this object, but a warning is issued in each case.</p>
    <h2 class="hasAnchor" id="see-also"><a class="anchor" href="#see-also"></a>See also</h2>

    <div class='dont-index'><p><code><a href='looi.html'>looi</a></code></p></div>

    <h2 class="hasAnchor" id="examples"><a class="anchor" href="#examples"></a>Examples</h2>
    <pre class="examples"><div class='input'><span class='co'>#Load assessment</span>
<span class='fu'><a href='https://rdrr.io/r/base/library.html'>library</a></span>(<span class='no'>FLSAM</span>)
<span class='fu'><a href='https://rdrr.io/r/utils/data.html'>data</a></span>(<span class='no'>NSH</span>)
<span class='fu'><a href='https://rdrr.io/r/utils/data.html'>data</a></span>(<span class='no'>NSH.sam</span>)

<span class='co'>#Run a retrospective analyses for 3 years</span>
<span class='no'>res</span> <span class='kw'>&lt;-</span> <span class='fu'><a href='retro.rd.html'>retro</a></span>(<span class='no'>NSH</span>,<span class='no'>NSH.tun</span>,<span class='no'>NSH.ctrl</span>,<span class='kw'>retro</span><span class='kw'>=</span><span class='fl'>3</span>)</div><div class='output co'>#&gt; Running retrospective...
#&gt; Error in setup.sam.data(surveys = surveysFLR, residual.fleets = residual.fleets,  : 
#&gt;   unused arguments (residual.fleets = residual.fleets, sum.residual.fleets = sum.fleets)</div><div class='output co'>#&gt; <span class='warning'>Warning: Retrospective for year 2011 failed</span></div><div class='output co'>#&gt; Error in setup.sam.data(surveys = surveysFLR, residual.fleets = residual.fleets,  : 
#&gt;   unused arguments (residual.fleets = residual.fleets, sum.residual.fleets = sum.fleets)</div><div class='output co'>#&gt; <span class='warning'>Warning: Retrospective for year 2010 failed</span></div><div class='output co'>#&gt; Error in setup.sam.data(surveys = surveysFLR, residual.fleets = residual.fleets,  : 
#&gt;   unused arguments (residual.fleets = residual.fleets, sum.residual.fleets = sum.fleets)</div><div class='output co'>#&gt; <span class='warning'>Warning: Retrospective for year 2009 failed</span></div><div class='output co'>#&gt; Error in setup.sam.data(surveys = surveysFLR, residual.fleets = residual.fleets,  : 
#&gt;   unused arguments (residual.fleets = residual.fleets, sum.residual.fleets = sum.fleets)</div><div class='output co'>#&gt; <span class='warning'>Warning: Retrospective for year 2008 failed</span></div><div class='input'>
<span class='co'>#Make an FLStocks object and plot the results</span>
<span class='no'>NSH.retro</span> <span class='kw'>&lt;-</span> <span class='no'>res</span> + <span class='no'>NSH</span>
<span class='fu'><a href='https://rdrr.io/r/graphics/plot.html'>plot</a></span>(<span class='no'>NSH.retro</span>)</div><div class='output co'>#&gt; <span class='error'>Error in dfs[[i]]: subscript out of bounds</span></div></pre>
  </div>
  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
    <h2>Contents</h2>
    <ul class="nav nav-pills nav-stacked">
      <li><a href="#arguments">Arguments</a></li>
      <li><a href="#details">Details</a></li>
      <li><a href="#value">Value</a></li>
      <li><a href="#see-also">See also</a></li>
      <li><a href="#examples">Examples</a></li>
    </ul>

    <h2>Author</h2>
    <p>Based on code by Laurence Kell, modified by Niels T. Hintzen and Mark R. Payne</p>
  </div>
</div>


      <footer>
      <div class="copyright">
  <p>Developed by N.T. Hintzen, M.R. Payne.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.4.1.</p>
</div>

      </footer>
   </div>

  


  </body>
</html>


